spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/chatgepeteco}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}

  ai:
    ollama:
      base-url: http://localhost:11434

springdoc:
  swagger-ui:
    enabled: true

server:
  port: 8080