spring:
  application:
    name: ChatGepeteco
  ai:
    ollama:
      base-url: http://localhost:11434/
      chat:
        model: gemma3:1b
cors:
  originPatterns: http://localhost:8080,http://localhost:8889,http://localhost:80,http://localhost:4200