spring:
  application:
    name: ChatGepeteco

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}

  ai:
    ollama:
      chat:
        model: ${OLLAMA_MODEL:gemma3:1b}

security:
  password:
    encoder:
      secret: ${PASSWORD_ENCODER_SECRET:CXVEuksocdUhvj04}
      iterations: 185000
      salt-length: 16
  jwt:
    token:
      secret-key: ${JWT_SECRET:CXVEuksocdUhvj04}
      expire-length: 36000000

springdoc:
  paths-to-match: /**
  swagger-ui:
    use-root-path: true

server:
  servlet:
    context-path: /api

cors:
  originPatterns: ${CORS_ORIGINS:http://localhost:4200}